
CREATE TABLE Aula (
ID INT PRIMARY KEY,
Nome VARCHAR(200)
)

-- INSERT INTO --

INSERT INTO Aula (ID, Nome)
VALUES 
(2,'Aula 0'),
(3,'Aula 2'),
(4,'Aula 3');




SELECT *
FROM Aula

-- CRIANDO UMA TABELA NOVA COM OS DADOS DE UMA EXISTENTE, COPIANDO --

SELECT * INTO Copya FROM Aula

SELECT *
FROM Copya

-- UPDATE --

UPDATE Copya
SET Nome = 'Mudei'
WHERE ID = 1 -- O WHERE � MTO IMPORTANTE, POIS SEM ELE VC ALTERA TODOS OS VALORES DA COLUNA, TEM QUE TER O WHERE PARA DAR A CONDI��O DE QUAL VALOR VC QUER ALTERAR --

SELECT *
FROM Copya

-- DELETE --

DELETE FROM Copya
WHERE Nome = 'Mudei' -- O WHERE � MTO IMPORTANTE, POIS SEM ELE VC ALTERA TODOS OS VALORES DA COLUNA, TEM QUE TER O WHERE PARA DAR A CONDI��O DE QUAL VALOR VC QUER ALTERAR --

SELECT *
FROM Copya

-- ALTER TABLE --

